server:
   port: 8080
   
spring:
   application:
      name: gateway
   cloud:
    consul:
      host: localhost
      port: 8500   
   boot:
      admin:
         client:
            url: http://localhost:7777     
            
management:
   endpoints:
      web:
         exposure:
            include: "*"
      health:
         show-details: always