server:
   port: 8082
   
spring:
   application:
      name: user
   cloud:
    consul:
      host: localhost
      port: 8500
   boot:
      admin:
         client:
            url: http://localhost:7777
            
management:
   endpoints:
      web:
         exposure:
            include: "*"
      health:
         show-details: always